import { generateDarkTheme } from './themes/dark';
import { generateLightTheme, generateRootFallback } from './themes/light';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const themesCss = [
  '/* Auto-generated by @flow/tokens build. Do not edit directly. */',
  '',
  generateRootFallback(),
  '',
  generateDarkTheme(),
  '',
  generateLightTheme(),
  '',
].join('\n');

const srcOutputPath = resolve(__dirname, 'generated-themes.css');
writeFileSync(srcOutputPath, themesCss, 'utf-8');
console.log(`Generated generated-themes.css at ${srcOutputPath}`);

const staticFiles = ['primitives.css', 'shadcn-bridge.css', 'portal-brand.css'];
const staticCss = staticFiles.map((f) => {
  const content = readFileSync(resolve(__dirname, f), 'utf-8');
  return `/* === ${f} === */\n${content}`;
}).join('\n\n');

const combinedCss = [
  '/* Auto-generated by @flow/tokens build. Do not edit directly. */',
  '',
  staticCss,
  '',
  themesCss,
  '',
  `@media (prefers-reduced-motion: reduce) {
  :root,
  [data-theme="dark"],
  [data-theme="light"] {
    --flow-duration-instant: 0ms;
    --flow-duration-fast: 0ms;
    --flow-duration-normal: 0ms;
    --flow-duration-expressive: 0ms;
    --flow-duration-ceremony: 100ms;
  }
}`,
  '',
].join('\n');

const distDir = resolve(__dirname, '../../dist');
mkdirSync(distDir, { recursive: true });

const outputPath = resolve(distDir, 'tokens.css');
writeFileSync(outputPath, combinedCss, 'utf-8');
console.log(`Generated tokens.css at ${outputPath}`);
