import { generateDarkTheme } from './themes/dark';
import { generateLightTheme } from './themes/light';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const css = [
  '/* Auto-generated by @flow/tokens build. Do not edit directly. */',
  '',
  generateDarkTheme(),
  '',
  generateLightTheme(),
  '',
].join('\n');

const outputPath = resolve(__dirname, '../../dist/tokens.css');
writeFileSync(outputPath, css, 'utf-8');
console.log(`Generated tokens.css at ${outputPath}`);
